-- File:        reset_dev_database.psql
-- Location:    musebms/tools/database_scripts/reset_dev_database.psql
-- Project:     Muse Systems Business Management System
--
-- Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
-- This file may include content copyrighted and licensed from third parties.
--
-- See the LICENSE file in the project root for license terms and conditions.
-- See the NOTICE file in the project root for copyright ownership information.
--
-- muse.information@musesystems.com :: https://muse.systems

-- Note that this script currently exists to support CI testing
-- A more robust script should be produced to walk users though
-- the initial setup of the starting database objects.
--
-- Do not use this script to setup a production environment.
\set ON_ERROR_STOP true
\c postgres

\ir drop_devtest_db_objects.psql

\ir bootstrap_database.psql
