sudo: false
language: elixir
elixir:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
otp_release:
  - 21.3
  - 22.1
matrix:
  exclude:
  - otp_release: 22.1
    elixir: 1.6
env:
  - "PLT_DIR=$HOME/.plt"
cache:
  directories:
    - _build
    - deps
    - $PLT_DIR
before_script:
  - "mkdir -p $PLT_DIR"
  - "mix do deps.get, dialyzer --plt"
  - "MIX_ENV=test mix deps.get"
script:
  - "mix compile-check"
  - "MIX_ENV=test mix do compile, test"
notifications:
  recipients:
    - paulschoenfelder@gmail.com
