-- Note that this script currently exists to support CI testing
-- A more robust script should be produced to walk users though
-- the initial setup of the global database and msbms_sys_login
-- user.
--
-- Do not use this script to setup a production environment.
\set ON_ERROR_STOP true
\c postgres

DROP DATABASE IF EXISTS msbms_syst_instance_mgr;

DROP ROLE IF EXISTS msbms_access;
DROP ROLE IF EXISTS msbms_syst_dba;

DROP ROLE IF EXISTS msbms_syst_instance_mgr_owner;
DROP ROLE IF EXISTS msbms_syst_instance_mgr_app_user;
DROP ROLE IF EXISTS msbms_syst_instance_mgr_api_user;

\ir bootstrap_database.psql
