# Source File: subplans.cmp_msbms_syst_authentication.toml
# Location:    musebms/database/all/subplans.cmp_msbms_syst_authentication.toml
# Project:     Muse Systems Business Management System
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com :: https://muse.systems

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    "cmp_msbms_syst_authentication/seed_data/initialize_enum_access_account_states.eex.sql",
    "cmp_msbms_syst_authentication/seed_data/initialize_enum_credential_types.eex.sql",
    "cmp_msbms_syst_authentication/seed_data/initialize_enum_identity_types.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst_data/syst_access_accounts/syst_access_accounts.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst_data/syst_identities/trig_b_iu_syst_identities_check_uniqueness.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst_data/syst_identities/syst_identities.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst_data/syst_credentials/syst_credentials.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst_data/syst_global_network_rules/trig_a_iu_syst_global_network_rule_ordering.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst_data/syst_global_network_rules/syst_global_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst_data/syst_owner_network_rules/trig_a_iu_syst_owner_network_rule_ordering.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst_data/syst_owner_network_rules/syst_owner_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst_data/syst_instance_network_rules/trig_a_iu_syst_instance_network_rule_ordering.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst_data/syst_instance_network_rules/syst_instance_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst_data/syst_global_password_rules/syst_global_password_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst_data/syst_owner_password_rules/syst_owner_password_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst_data/syst_disallowed_passwords/syst_disallowed_passwords.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst_data/syst_password_history/syst_password_history.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst_data/syst_access_account_instance_assocs/syst_access_account_instance_assocs.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_access_accounts/trig_i_i_syst_access_accounts.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_access_accounts/trig_i_u_syst_access_accounts.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_access_accounts/trig_i_d_syst_access_accounts.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_access_accounts/syst_access_accounts.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_access_account_instance_assocs/trig_i_i_syst_access_account_instance_assocs.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_access_account_instance_assocs/trig_i_u_syst_access_account_instance_assocs.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_access_account_instance_assocs/trig_i_d_syst_access_account_instance_assocs.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_access_account_instance_assocs/syst_access_account_instance_assocs.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_identities/trig_i_i_syst_identities.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_identities/trig_i_u_syst_identities.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_identities/trig_i_d_syst_identities.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_identities/syst_identities.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_credentials/trig_i_i_syst_credentials.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_credentials/trig_i_u_syst_credentials.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_credentials/trig_i_d_syst_credentials.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_credentials/syst_credentials.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_global_network_rules/trig_i_i_syst_global_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_global_network_rules/trig_i_u_syst_global_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_global_network_rules/trig_i_d_syst_global_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_global_network_rules/syst_global_network_rules.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_owner_network_rules/trig_i_i_syst_owner_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_owner_network_rules/trig_i_u_syst_owner_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_owner_network_rules/trig_i_d_syst_owner_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_owner_network_rules/syst_owner_network_rules.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_instance_network_rules/trig_i_i_syst_instance_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_instance_network_rules/trig_i_u_syst_instance_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_instance_network_rules/trig_i_d_syst_instance_network_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_instance_network_rules/syst_instance_network_rules.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_global_password_rules/trig_i_i_syst_global_password_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_global_password_rules/trig_i_u_syst_global_password_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_global_password_rules/trig_i_d_syst_global_password_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_global_password_rules/syst_global_password_rules.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_owner_password_rules/trig_i_i_syst_owner_password_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_owner_password_rules/trig_i_u_syst_owner_password_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_owner_password_rules/trig_i_d_syst_owner_password_rules.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_owner_password_rules/syst_owner_password_rules.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_disallowed_passwords/trig_i_i_syst_disallowed_passwords.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_disallowed_passwords/trig_i_u_syst_disallowed_passwords.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_disallowed_passwords/trig_i_d_syst_disallowed_passwords.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_disallowed_passwords/syst_disallowed_passwords.eex.sql",

    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_password_history/trig_i_i_syst_password_history.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_password_history/trig_i_u_syst_password_history.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_password_history/trig_i_d_syst_password_history.eex.sql",
    "cmp_msbms_syst_authentication/msbms_syst/api_views/syst_password_history/syst_password_history.eex.sql",
]
