# Source File: subplans.mscmp_syst_enums.toml
# Location:    musebms/database/components/system/mscmp_syst_enums/subplans.mscmp_syst_enums.toml
# Project:     Muse Systems Business Management System
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com :: https://muse.systems

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    "components/system/mscmp_syst_enums/ms_syst_data/syst_enums/syst_enums.eex.sql",

    "components/system/mscmp_syst_enums/ms_syst_data/syst_enum_functional_types/trig_b_i_syst_enum_functional_type_validate_new_allowed.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst_data/syst_enum_functional_types/syst_enum_functional_types.eex.sql",

    "components/system/mscmp_syst_enums/ms_syst_data/syst_enum_items/trig_b_i_syst_enum_items_maintain_sort_order.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst_data/syst_enum_items/trig_b_iu_syst_enum_items_validate_functional_types.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst_data/syst_enum_items/trig_a_iu_syst_enum_items_maintain_sort_order.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst_data/syst_enum_items/syst_enum_items.eex.sql",

    "components/system/mscmp_syst_enums/ms_syst_priv/functions/initialize_enum.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst_priv/trigger_functions/trig_a_iu_enum_item_check.eex.sql",

    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enums/trig_i_i_syst_enums.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enums/trig_i_u_syst_enums.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enums/trig_i_d_syst_enums.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enums/syst_enums.eex.sql",

    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enum_functional_types/trig_i_i_syst_enum_functional_types.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enum_functional_types/trig_i_u_syst_enum_functional_types.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enum_functional_types/trig_i_d_syst_enum_functional_types.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enum_functional_types/syst_enum_functional_types.eex.sql",

    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enum_items/trig_i_i_syst_enum_items.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enum_items/trig_i_u_syst_enum_items.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enum_items/trig_i_d_syst_enum_items.eex.sql",
    "components/system/mscmp_syst_enums/ms_syst/api_views/syst_enum_items/syst_enum_items.eex.sql",
]
