# File:        subplans.mscmp_core_groups.toml
# Location:    musebms/database/components/application/mscmp_core_groups/subplans.mscmp_core_groups.toml
# Project:     Muse Systems Business Management System
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com :: https://muse.systems

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    "components/application/mscmp_core_groups/ms_appl_data/supp_group_functional_types/supp_group_functional_types.eex.sql",
    "components/application/mscmp_core_groups/ms_appl_data/supp_group_types/supp_group_types.eex.sql",
    "components/application/mscmp_core_groups/ms_appl_data/supp_group_type_items/trig_b_iu_supp_group_type_items_depth_maint.eex.sql",
    "components/application/mscmp_core_groups/ms_appl_data/supp_group_type_items/supp_group_type_items.eex.sql",
    "components/application/mscmp_core_groups/ms_appl_data/supp_groups/trig_b_iu_supp_groups_validate_parent_group_type_item.eex.sql",
    "components/application/mscmp_core_groups/ms_appl_data/supp_groups/supp_groups.eex.sql",

    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_functional_types/trig_i_i_supp_group_functional_types.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_functional_types/trig_i_u_supp_group_functional_types.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_functional_types/trig_i_d_supp_group_functional_types.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_functional_types/supp_group_functional_types.eex.sql",

    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_types/trig_i_i_supp_group_types.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_types/trig_i_u_supp_group_types.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_types/trig_i_d_supp_group_types.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_types/supp_group_types.eex.sql",

    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_type_items/trig_i_i_supp_group_type_items.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_type_items/trig_i_u_supp_group_type_items.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_type_items/trig_i_d_supp_group_type_items.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_group_type_items/supp_group_type_items.eex.sql",

    "components/application/mscmp_core_groups/ms_appl/api_views/supp_groups/trig_i_i_supp_groups.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_groups/trig_i_u_supp_groups.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_groups/trig_i_d_supp_groups.eex.sql",
    "components/application/mscmp_core_groups/ms_appl/api_views/supp_groups/supp_groups.eex.sql",
]
