baseURL = "https://docs.muse.systems/musebms"
languageCode = "en-us"
title = "Muse Systems Business Management System Documentation"

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.113.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false