-- File:        app1.01.01.001.0000MT.000.eex.sql
-- Location:    musebms/database/components/system/msbms_syst_instance_mgr/testing_support/app1/app1.01.01.001.0000MT.000.eex.sql
-- Project:     Muse Systems Business Management System
--
-- Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
-- This file may include content copyrighted and licensed from third parties.
--
-- See the LICENSE file in the project root for license terms and conditions.
-- See the NOTICE file in the project root for copyright ownership information.
--
-- muse.information@musesystems.com  :: https://muse.systems

DO
$MIGRATION$
    BEGIN
            CREATE TABLE testing.test_detail
            (
                 id
                    bigint
                    GENERATED BY DEFAULT AS IDENTITY
                    CONSTRAINT test_detail_pk PRIMARY KEY
                ,test_header_id
                    bigint
                    NOT NULL
                    CONSTRAINT test_detail_header_fk
                        REFERENCES testing.test_header (id)
                        ON DELETE CASCADE
                ,test_detail_value
                    text
                    NOT NULL
            );

            ALTER TABLE testing.test_detail OWNER TO <%= app1_owner %>;

            REVOKE ALL ON TABLE testing.test_detail FROM public;
            GRANT ALL ON TABLE testing.test_detail TO <%= app1_owner %>;
            GRANT ALL ON TABLE testing.test_detail TO <%= app1_appusr %>;
            GRANT ALL ON TABLE testing.test_detail TO <%= app1_apiusr %>;

            COMMENT ON
                TABLE testing.test_detail IS
            $DOC$A testing detail table for MsbmsSystInstanceMgr integration testing.$DOC$;

            COMMENT ON
                COLUMN testing.test_detail.id IS
            $DOC$The record's primary key.  The definitive identifier of the record in the system.$DOC$;

            COMMENT ON
                COLUMN testing.test_detail.test_header_id IS
            $DOC$A reference to a parent testing.test_header record.$DOC$;

            COMMENT ON
                COLUMN testing.test_detail.test_detail_value IS
            $DOC$A simple testing value which has no well defined meaning.$DOC$;

    END;
$MIGRATION$;
