-- File:        reset_mscmp_syst_db.psql
-- Location:    musebms/app_server/components/system/mscmp_syst_db/database/utility/reset_mscmp_syst_db.psql
-- Project:     Muse Systems Business Management System
--
-- Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
-- This file may include content copyrighted and licensed from third parties.
--
-- See the LICENSE file in the project root for license terms and conditions.
-- See the NOTICE file in the project root for copyright ownership information.
--
-- muse.information@musesystems.com :: https://muse.systems

-- Note that this script currently exists to support CI testing
-- A more robust script should be produced to walk users though
-- the initial setup of the global database and ms_sys_login
-- user.
--
-- Do not use this script to setup a production environment.

DROP DATABASE IF EXISTS ms_test_type_one;
DROP DATABASE IF EXISTS ms_test_type_four;

DROP ROLE IF EXISTS ms_type_one_role_01;
DROP ROLE IF EXISTS ms_type_one_role_02;
DROP ROLE IF EXISTS ms_type_one_role_03;
DROP ROLE IF EXISTS ms_type_one_role_04;
DROP ROLE IF EXISTS ms_test_type_one_owner;

DROP ROLE IF EXISTS ms_type_four_role_01;
DROP ROLE IF EXISTS ms_test_type_four_owner;
