-- Note that this script currently exists to support CI testing
-- A more robust script should be produced to walk users though
-- the initial setup of the mbms_global database and ms_sys_login
-- user.
--
-- Do not use this script to setup a production environment.
\set ON_ERROR_STOP true
\c postgres

DROP DATABASE IF EXISTS ms_test_type_one;
DROP DATABASE IF EXISTS ms_test_type_four;

DROP FUNCTION IF EXISTS ms_syst.create_login_role(text, text, text);
DROP FUNCTION IF EXISTS ms_syst.create_nonlogin_role(text, text);
DROP FUNCTION IF EXISTS ms_syst.drop_role(text);

DROP SCHEMA IF EXISTS ms_syst;

DROP ROLE IF EXISTS ms_syst_access;
DROP ROLE IF EXISTS ms_syst_privileged;
DROP ROLE IF EXISTS ms_syst_managable;
DROP ROLE IF EXISTS ms_syst_owner;

DROP ROLE IF EXISTS ms_type_one_role_01;
DROP ROLE IF EXISTS ms_type_one_role_02;
DROP ROLE IF EXISTS ms_type_one_role_03;
DROP ROLE IF EXISTS ms_type_one_role_04;
DROP ROLE IF EXISTS ms_test_type_one_owner;

DROP ROLE IF EXISTS ms_type_four_role_01;
DROP ROLE IF EXISTS ms_test_type_four_owner;

\ir ../../../../../../tools/database_scripts/bootstrap_database.psql
