# File:        subplans.mscmp_syst_session.toml
# Location:    musebms/database/components/system/mscmp_syst_session/subplans.mscmp_syst_session.toml
# Project:     Muse Systems Business Management System
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com :: https://muse.systems

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    "components/system/mscmp_syst_session/ms_syst_data/syst_sessions/syst_sessions.eex.sql",

    "components/system/mscmp_syst_session/ms_syst/api_views/syst_sessions/trig_i_i_syst_sessions.eex.sql",
    "components/system/mscmp_syst_session/ms_syst/api_views/syst_sessions/trig_i_u_syst_sessions.eex.sql",
    "components/system/mscmp_syst_session/ms_syst/api_views/syst_sessions/trig_i_d_syst_sessions.eex.sql",
    "components/system/mscmp_syst_session/ms_syst/api_views/syst_sessions/syst_sessions.eex.sql",
]
