# File:        subplans.mscmp_syst_mcp_perms.toml
# Location:    musebms/database/components/system/mscmp_syst_mcp_perms/subplans.mscmp_syst_mcp_perms.toml
# Project:     Muse Systems Business Management System
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com :: https://muse.systems

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    "components/system/mscmp_syst_mcp_perms/seed_data/syst_perm_functional_types.eex.sql",
    "components/system/mscmp_syst_mcp_perms/seed_data/syst_perms.eex.sql",
    "components/system/mscmp_syst_mcp_perms/seed_data/syst_perm_roles.eex.sql",
    "components/system/mscmp_syst_mcp_perms/seed_data/syst_perm_role_grants.eex.sql",

]
