-- Note that this script currently exists to support CI testing
-- A more robust script should be produced to walk users though
-- the initial setup of the global database and msbms_sys_login
-- user.
--
-- Do not use this script to setup a production environment.
\set ON_ERROR_STOP true
\c postgres

DROP DATABASE IF EXISTS mscmp_syst_instance;

DROP ROLE IF EXISTS ms_syst_access;
DROP ROLE IF EXISTS ms_syst_dba;

DROP ROLE IF EXISTS mscmp_syst_instance_owner;
DROP ROLE IF EXISTS mscmp_syst_instance_app_user;

DROP DATABASE IF EXISTS app1_owner1;

DROP ROLE IF EXISTS app1_owner1_app1_owner;
DROP ROLE IF EXISTS app1_owner1_app1_appusr;
DROP ROLE IF EXISTS app1_owner1_app1_apiusr;

DROP DATABASE IF EXISTS app1_owner2;

DROP ROLE IF EXISTS app1_owner2_app1_owner;
DROP ROLE IF EXISTS app1_owner2_app1_appusr;
DROP ROLE IF EXISTS app1_owner2_app1_apiusr;

DROP DATABASE IF EXISTS app2_owner1;

DROP ROLE IF EXISTS app2_owner1_app2_owner;
DROP ROLE IF EXISTS app2_owner1_app2_appusr;
DROP ROLE IF EXISTS app2_owner1_app2_apiusr;

DROP DATABASE IF EXISTS app2_owner2;

DROP ROLE IF EXISTS app2_owner2_app2_owner;
DROP ROLE IF EXISTS app2_owner2_app2_appusr;
DROP ROLE IF EXISTS app2_owner2_app2_apiusr;

\ir bootstrap_database.psql
