# Source File: mscmp_syst_session.ex
# Location:    musebms/app_server/components/system/mscmp_syst_session/lib/api/mscmp_syst_session.ex
# Project:     Muse Systems Business Management System
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com :: https://muse.systems

defmodule MscmpSystSession do
  @external_resource "README.md"
  @moduledoc Path.join([__DIR__, "..", "..", "README.md"])
             |> File.read!()
             |> String.split("<!-- MDOC !-->")
             |> Enum.fetch!(1)

  alias MscmpSystError.Types.Context, as: ErrorContext
  alias MscmpSystSession.Impl
  alias MscmpSystSession.Types

  ##############################################################################
  #
  # Options Definition
  #
  #

  option_defs = [
    session_name_length: [
      type: :pos_integer,
      default: 16,
      doc: """
      The number of characters to use for the session name.
      """
    ],
    session_name_tokens: [
      type: {:or, [{:list, :any}, {:in, [:alphanum, :mixed_alphanum, :b32e, :b32c]}]},
      type_doc: "t:Msutils.String.Types.tokens/0",
      type_spec: quote(do: Msutils.String.Types.tokens()),
      default: :mixed_alphanum,
      doc: """
      Specifies the pre-defined token set or a set of tokens to use for creating
      session names.  If using a custom token set, the set must be expressed as
      an Erlang charlist.
      """
    ],
    session_name: [
      type: :string,
      type_spec: quote(do: MscmpSystSession.Types.session_name()),
      doc: """
      A value to use for the session name rather than letting the system create
      a random session name.  If this value is not provided, it will be
      defaulted with a random value as generated by `generate_session_name/0`.
      """
    ],
    expires_after: [
      type: :non_neg_integer,
      default: 3600,
      doc: """
      The number of seconds for which the session will be considered valid.  In
      seconds.
      """
    ],
    db_timeout: [
      type: :pos_integer,
      default: 300,
      doc: """
      The number of seconds to wait for a response from the database.
      """
    ]
  ]

  ##############################################################################
  #
  # generate_session_name
  #
  #

  @generate_session_name_opts NimbleOptions.new!(
                                Keyword.take(option_defs, [
                                  :session_name_length,
                                  :session_name_tokens
                                ])
                              )

  @doc section: :session_management
  @doc """
  Generates a random Session Name using the current formulation for automatic
  session name generation.

  Currently generated Session Names are strings of 16 random characters using a
  mixed case, alphanumeric character set.

  ## Parameters

    * `opts` - A keyword list of options to use for the Session Name generation.

  ## Options

    #{NimbleOptions.docs(@generate_session_name_opts)}

  ## Examples

  Generating a random name.

      iex> session_name = MscmpSystSession.generate_session_name()
      iex> String.length(session_name) == 16
      true
  """
  @spec generate_session_name() :: Types.session_name()
  @spec generate_session_name(Keyword.t()) :: Types.session_name()
  def generate_session_name(opts \\ []) do
    opts = NimbleOptions.validate!(opts, @generate_session_name_opts)
    Impl.DbSession.generate_session_name(opts)
  end

  ##############################################################################
  #
  # create_session
  #
  #

  @create_session_opts NimbleOptions.new!(
                         Keyword.take(option_defs, [:session_name, :expires_after])
                       )

  @doc section: :session_management
  @doc """
  Creates a new session returning the session name for future reference.

  Using a starting set of data and a expiration period, creates a new Session
  record.  The return value is either a success tuple including the generated
  name of the session record or an error tuple explaining the failure.

  Currently, the Session name is an automatically generated random 96 bytes run
  through base 64 encoding.

  ## Parameters

    * `session_data` - the initial Session Data to use in creating the new
    Session record in the database.  Currently the expectation is that this
    value will be any arbitrary `Map`.  This parameter is required.

    * `opts` - a Keyword List of optional parameters.

  ## Options

    #{NimbleOptions.docs(@create_session_opts)}

  ## Examples

  Creating a new Session with the default expiration time.

      iex> {:ok, session_name} =
      ...>   MscmpSystSession.create_session(%{test: "test"})
      iex> is_binary(session_name)
      true
  """
  @spec create_session(map()) :: {:ok, Types.session_name()} | {:error, Mserror.SessionError.t()}
  @spec create_session(map(), Keyword.t()) ::
          {:ok, Types.session_name()} | {:error, Mserror.SessionError.t()}
  def create_session(session_data, opts \\ []) do
    validated_opts = NimbleOptions.validate!(opts, @create_session_opts)

    case Impl.DbSession.create_session(session_data, validated_opts) do
      {:ok, result} ->
        {:ok, result}

      error ->
        {:error,
         Mserror.SessionError.new(:session_management, "Error creating session",
           parse_error: error,
           context: %ErrorContext{
             origin: {__MODULE__, :create_session, 2},
             parameters: %{session_data: session_data, opts: opts}
           }
         )}
    end
  end

  ##############################################################################
  #
  # get_session
  #
  #

  @get_session_opts NimbleOptions.new!(Keyword.take(option_defs, [:expires_after]))

  @doc section: :session_management
  @doc """
  Retrieves the Session Data for the named Session and resets the Session
  Expiration.

  It should be noted that reading a Session will also refresh the expiration of
  that Session's expiration date.

  Trying to retrieve the Session data of an already expired Session results in
  an error type with the `:not_found` cause being returned.

  ## Parameters

    * `session_name` - the Session Name that was generated by `create_session/2`
    at Session create time.  This argument is required.

    * `opts` - a Keyword List of optional parameters.

  ## Options

    #{NimbleOptions.docs(@get_session_opts)}

  ## Examples

  Retrieving a Session and setting the renewed expiration date/time to 30
  minutes from retrieval time.

      iex> {:ok, %{}} = MscmpSystSession.get_session("example_session", expires_after: 1800)

  Attempting to retrieve an expired Session returns the not found value.

      iex> {:error, %Mserror.SessionError{cause: :not_found}} =
      ...>   MscmpSystSession.get_session("example_expired_session")
  """
  @spec get_session(Types.session_name()) ::
          {:ok, Types.session_data()} | {:error, Mserror.SessionError.t()}
  @spec get_session(Types.session_name(), Keyword.t()) ::
          {:ok, Types.session_data()} | {:error, Mserror.SessionError.t()}
  def get_session(session_name, opts \\ []) do
    validated_opts = NimbleOptions.validate!(opts, @get_session_opts)

    case Impl.DbSession.get_session(session_name, validated_opts) do
      {:ok, result} ->
        {:ok, result}

      error ->
        {:error,
         Mserror.SessionError.new(:session_management, "Error getting session",
           parse_error: error,
           context: %ErrorContext{
             origin: {__MODULE__, :get_session, 2},
             parameters: %{session_name: session_name, opts: opts}
           }
         )}
    end
  end

  ##############################################################################
  #
  # refresh_session_expiration
  #
  #

  @refresh_session_expiration_opts NimbleOptions.new!(Keyword.take(option_defs, [:expires_after]))

  @doc section: :session_management
  @doc """
  Refreshes the Session expiration date/time of the identified record.

  The function only returns its success status absent any data.

  Do note that all other interactions with the Session will also refresh the
  Session expiration date/time so in many cases there is no need to call this
  function explicitly.  Typically you'd only call this function if you've had
  interaction with the user, but not needed to access the session for some time.

  Trying to refresh the expiration date/time of an already expired Session will
  be treated as a "not found" record.

  ## Parameters

    * `session_name` - the Session Name that was generated by `create_session/2`
    at Session create time.  This argument is required.

    * `opts` - a Keyword List of optional parameters.

  ## Options

    #{NimbleOptions.docs(@refresh_session_expiration_opts)}

  ## Examples

  Refreshing a Session expiration date/time to 30 minutes from refresh time.

      iex> MscmpSystSession.refresh_session_expiration("example_session", expires_after: 1800)
      :ok

  Attempting to refresh an already expired Session returns the not found value.

      iex> {:error, %Mserror.SessionError{cause: :not_found}} =
      ...>   MscmpSystSession.refresh_session_expiration("example_expired_session")
  """
  @spec refresh_session_expiration(Types.session_name()) ::
          :ok | {:error, Mserror.SessionError.t()}
  @spec refresh_session_expiration(Types.session_name(), Keyword.t()) ::
          :ok | {:error, Mserror.SessionError.t()}
  def refresh_session_expiration(session_name, opts \\ []) do
    validated_opts = NimbleOptions.validate!(opts, @refresh_session_expiration_opts)

    case Impl.DbSession.refresh_session_expiration(session_name, validated_opts) do
      :ok ->
        :ok

      error ->
        {:error,
         Mserror.SessionError.new(:session_management, "Error refreshing session expiration",
           parse_error: error,
           context: %ErrorContext{
             origin: {__MODULE__, :refresh_session_expiration, 2},
             parameters: %{session_name: session_name, opts: opts}
           }
         )}
    end
  end

  ##############################################################################
  #
  # update_session
  #
  #

  @update_session_opts NimbleOptions.new!(Keyword.take(option_defs, [:expires_after]))

  @doc section: :session_management
  @doc """
  Replaces the Session Data of the named Session record with the Session Data
  provided.

  As with other kinds of interactions with the Session, updating the Session
  data will also update the expiration date/time.

  Attempting to update the Session Data of an already expired Session will
  be treated as attempting to update a not found record.

  ## Parameters

    * `session_name` - the Session Name that was generated by `create_session/2`
    at Session create time.  This argument is required.

    * `session_data` - the updated Session Data which replaces the existing
    Session Data.  Currently the expectation is that this value will be any
    arbitrary `Map`.  This argument is required.

    * `opts` - a Keyword List of optional parameters.

  ## Options

    #{NimbleOptions.docs(@update_session_opts)}

  ## Examples

  Updating a Session with new data and resetting the expiration date/time to
  30 minutes from update time.

      iex> MscmpSystSession.update_session("example_update_session", %{updated_key: "updated_value"},
      ...>   expires_after: 1800)
      :ok
      iex> MscmpSystSession.get_session("example_update_session")
      {:ok, %{"updated_key" => "updated_value"}}

  Attempting to update an already expired Session returns the not found value.

      iex> {:error, %Mserror.SessionError{cause: :not_found}} =
      ...>   MscmpSystSession.update_session("example_expired_session", %{updated_key: "updated_value"})
  """
  @spec update_session(Types.session_name(), Types.session_data()) ::
          :ok | {:error, Mserror.SessionError.t()}
  @spec update_session(Types.session_name(), Types.session_data(), Keyword.t()) ::
          :ok | {:error, Mserror.SessionError.t()}
  def update_session(session_name, session_data, opts \\ []) do
    validated_opts = NimbleOptions.validate!(opts, @update_session_opts)

    case Impl.DbSession.update_session(session_name, session_data, validated_opts) do
      :ok ->
        :ok

      error ->
        {:error,
         Mserror.SessionError.new(:session_management, "Error updating session",
           parse_error: error,
           context: %ErrorContext{
             origin: {__MODULE__, :update_session, 3},
             parameters: %{session_name: session_name, session_data: session_data, opts: opts}
           }
         )}
    end
  end

  ##############################################################################
  #
  # delete_session
  #
  #

  @doc section: :session_management
  @doc """
  Deletes the named Session record from the database.

  This is the de facto method for terminating a session.

  Unlike the other functions in this module which treat expired Session records
  as though they've not been found, deleting an expired Session is permitted and
  will return the same value as deleting an unexpired Session record.

  ## Parameters

    * `session_name` - the Session Name that was generated by `create_session/2`
    at Session create time.  This argument is required.

  ## Examples

  Deleting a Session record.

      iex> MscmpSystSession.delete_session("example_delete_session")
      :ok

  Attempting to delete a nonexistent Session returns the not found value.

      iex> {:error, %Mserror.SessionError{cause: :not_found}} =
      ...>   MscmpSystSession.delete_session("nonexistent_session")

  """
  @spec delete_session(Types.session_name()) :: :ok | {:error, Mserror.SessionError.t()}
  def delete_session(session_name) do
    case Impl.DbSession.delete_session(session_name) do
      :ok ->
        :ok

      error ->
        {:error,
         Mserror.SessionError.new(:session_management, "Error deleting session",
           parse_error: error,
           context: %ErrorContext{
             origin: {__MODULE__, :delete_session, 1},
             parameters: %{session_name: session_name}
           }
         )}
    end
  end

  ##############################################################################
  #
  # purge_expired_sessions
  #
  #

  @purge_expired_sessions_opts NimbleOptions.new!(Keyword.take(option_defs, [:db_timeout]))

  @doc section: :session_management
  @doc """
  Purges the database of previously expired Session records.

  The intention of this function is for it to be called on a periodic, scheduled
  basis in order to keep the system clean of expired Sessions.  The expectations
  are that the purge process may take some time.  Currently, 4 minutes are
  allotted for the running of the process prior to timing out, so a schedule
  more aggressive than once every 5 minutes is not advised.

  ## Parameters

    * `opts` - a Keyword List of optional parameters.

  ## Options

    #{NimbleOptions.docs(@purge_expired_sessions_opts)}
  """
  @spec purge_expired_sessions() :: :ok | {:error, Mserror.SessionError.t()}
  @spec purge_expired_sessions(Keyword.t()) :: :ok | {:error, Mserror.SessionError.t()}
  def purge_expired_sessions(opts \\ []) do
    validated_opts = NimbleOptions.validate!(opts, @purge_expired_sessions_opts)

    case Impl.DbSession.purge_expired_sessions(validated_opts) do
      :ok ->
        :ok

      error ->
        {:error,
         Mserror.SessionError.new(:session_management, "Error purging expired sessions",
           parse_error: error,
           context: %ErrorContext{
             origin: {__MODULE__, :purge_expired_sessions, 1},
             parameters: %{opts: opts}
           }
         )}
    end
  end
end
