# Source File: buildplans.msbms_syst_instance_mgr.toml
# Location:    musebms/database/buildplans.msbms_syst_instance_mgr.toml
# Project:     musebms
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com  : : https: //muse.systems

##
##  NOTE:  This build plan exists only to facilitate automated testing,
##         continuous integration, and other similar development & testing
##         activities.  It is not used to build released software.
##

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 821
sponsor_modification = 0
load_files = [
    #
    # Database Preparation and Common Facilities Load
    #

    "cmp_msbms_syst_enums/testing_support/database_initial_setup.eex.sql",
    "cmp_msbms_syst_enums/testing_support/create_database_schemata.eex.sql",

    "all/msbms_syst_priv/collations/variant_insensitive.eex.sql",
    "all/msbms_syst_priv/functions/get_exception_details.eex.sql",
    "all/msbms_syst_priv/trigger_functions/trig_b_iu_set_diagnostic_columns.eex.sql",

    #
    # MsbmsSystEnums Module
    #

    "cmp_msbms_syst_enums/msbms_syst_data/syst_enums/syst_enums.eex.sql",

    "cmp_msbms_syst_enums/msbms_syst_data/syst_enum_functional_types/trig_b_i_syst_enum_functional_type_validate_new_allowed.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst_data/syst_enum_functional_types/syst_enum_functional_types.eex.sql",

    "cmp_msbms_syst_enums/msbms_syst_data/syst_enum_items/trig_b_i_syst_enum_items_maintain_sort_order.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst_data/syst_enum_items/trig_b_iu_syst_enum_items_validate_functional_types.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst_data/syst_enum_items/trig_a_iu_syst_enum_items_maintain_sort_order.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst_data/syst_enum_items/syst_enum_items.eex.sql",

    "cmp_msbms_syst_enums/msbms_syst_priv/functions/initialize_enum.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst_priv/trigger_functions/trig_a_iu_enum_item_check.eex.sql",

    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enums/trig_i_i_syst_enums.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enums/trig_i_u_syst_enums.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enums/trig_i_d_syst_enums.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enums/syst_enums.eex.sql",

    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enum_functional_types/trig_i_i_syst_enum_functional_types.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enum_functional_types/trig_i_u_syst_enum_functional_types.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enum_functional_types/trig_i_d_syst_enum_functional_types.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enum_functional_types/syst_enum_functional_types.eex.sql",

    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enum_items/trig_i_i_syst_enum_items.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enum_items/trig_i_u_syst_enum_items.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enum_items/trig_i_d_syst_enum_items.eex.sql",
    "cmp_msbms_syst_enums/msbms_syst/api_views/syst_enum_items/syst_enum_items.eex.sql",

    #
    # MsbmsSystInstanceMgr Module
    #

    "cmp_msbms_syst_instance_mgr/msbms_syst_data/syst_applications/trig_b_d_syst_applications_delete_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst_data/syst_applications/syst_applications.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst_data/syst_application_contexts/trig_b_iud_syst_application_contexts_validate_owner_context.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst_data/syst_application_contexts/syst_application_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst_data/syst_instance_type_applications/trig_a_i_syst_instance_type_apps_create_inst_type_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst_data/syst_instance_type_applications/syst_instance_type_applications.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst_data/syst_owners/syst_owners.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst_data/syst_instances/trig_a_i_syst_instances_create_instance_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst_data/syst_instances/syst_instances.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst_data/syst_instance_type_contexts/syst_instance_type_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst_data/syst_instance_contexts/syst_instance_contexts.eex.sql",

    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_applications/syst_applications.eex.sql",

    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_application_contexts/trig_i_u_syst_application_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_application_contexts/syst_application_contexts.eex.sql",

    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_owners/trig_i_i_syst_owners.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_owners/trig_i_u_syst_owners.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_owners/trig_i_d_syst_owners.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_owners/syst_owners.eex.sql",

    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_type_applications/trig_i_i_syst_instance_type_applications.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_type_applications/trig_i_u_syst_instance_type_applications.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_type_applications/trig_i_d_syst_instance_type_applications.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_type_applications/syst_instance_type_applications.eex.sql",

    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_type_contexts/trig_i_i_syst_instance_type_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_type_contexts/trig_i_u_syst_instance_type_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_type_contexts/trig_i_d_syst_instance_type_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_type_contexts/syst_instance_type_contexts.eex.sql",

    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instances/trig_i_i_syst_instances.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instances/trig_i_u_syst_instances.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instances/trig_i_d_syst_instances.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instances/syst_instances.eex.sql",

    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_contexts/trig_i_i_syst_instance_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_contexts/trig_i_u_syst_instance_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_contexts/trig_i_d_syst_instance_contexts.eex.sql",
    "cmp_msbms_syst_instance_mgr/msbms_syst/api_views/syst_instance_contexts/syst_instance_contexts.eex.sql",

    "cmp_msbms_syst_instance_mgr/seed_data/initialize_enum_owner_states.eex.sql",
    "cmp_msbms_syst_instance_mgr/seed_data/initialize_enum_instance_states.eex.sql",
    "cmp_msbms_syst_instance_mgr/seed_data/initialize_enum_instance_types.eex.sql",

    #
    # Testing Data Setup
    #

    "cmp_msbms_syst_instance_mgr/testing_support/test_privileges.eex.sql",
    "cmp_msbms_syst_instance_mgr/testing_support/test_data_unit_test.eex.sql",
]
