# Source File: manifest_instance.toml
# Location:    musebms/database/manifest_instance.toml
# Project:     musebms
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com  : : https: //muse.systems

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    "instance/dbinit/database_initial_setup.eex.sql",
    "instance/dbinit/create_database_schemata.eex.sql",
    "common/msbms_syst_priv/functions/get_exception_details.eex.sql",
    "common/msbms_syst_priv/trigger_functions/trig_b_iu_set_diagnostic_columns.eex.sql",
    "common/msbms_syst_data/tables/syst_modules.eex.sql",
    "common/msbms_syst_data/tables/syst_feature_types.eex.sql",
    "common/msbms_syst_data/tables/syst_features.eex.sql",
    "common/msbms_syst_data/tables/syst_relations.eex.sql",
    "instance/msbms_syst_data/tables/conf_system_settings.eex.sql",
    "instance/msbms_syst_data/tables/syst_feature_relation_assigns.eex.sql",
    "instance/msbms_syst_data/tables/enum_interface_types.eex.sql",
    "instance/msbms_syst_data/tables/enum_interaction_types.eex.sql",
    "instance/msbms_syst_data/tables/enum_login_states.eex.sql",
    "instance/msbms_syst_data/tables/syst_interaction_logs.eex.sql",
    "instance/msbms_appl_data/tables/conf_global_settings.eex.sql",
    "instance/msbms_appl_data/tables/enum_entity_states.eex.sql",
    "instance/msbms_appl_data/tables/enum_entity_types.eex.sql",
    "instance/msbms_appl_data/tables/enum_person_states.eex.sql",
    "instance/msbms_appl_data/tables/enum_person_types.eex.sql",
    "instance/msbms_appl_data/tables/enum_place_states.eex.sql",
    "instance/msbms_appl_data/tables/enum_place_types.eex.sql",
    "instance/msbms_appl_data/tables/enum_address_states.eex.sql",
    "instance/msbms_appl_data/tables/enum_entity_place_roles.eex.sql",
    "instance/msbms_appl_data/tables/enum_entity_person_roles.eex.sql",
    "instance/msbms_appl_data/tables/enum_place_address_roles.eex.sql",
    "instance/msbms_appl_data/tables/enum_contact_states.eex.sql",
    "instance/msbms_appl_data/tables/enum_contact_types.eex.sql",
    "instance/msbms_appl_data/tables/enum_person_contact_roles.eex.sql",
    "instance/msbms_appl_data/tables/enum_fiscal_year_states.eex.sql",
    "instance/msbms_appl_data/tables/enum_fiscal_year_types.eex.sql",
    "instance/msbms_appl_data/tables/enum_fiscal_period_states.eex.sql",
    "instance/msbms_appl_data/tables/conf_address_formats.eex.sql",
    "instance/msbms_appl_data/tables/conf_phone_formats.eex.sql",
    "instance/msbms_appl_data/tables/conf_name_formats.eex.sql",
    "instance/msbms_appl_data/tables/mstr_countries.eex.sql",
    "instance/msbms_appl_data/tables/mstr_country_address_format_assocs.eex.sql",
    "instance/msbms_appl_data/tables/mstr_country_phone_format_assocs.eex.sql",
    "instance/msbms_appl_data/tables/mstr_country_name_format_assocs.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entities.eex.sql",
    "instance/msbms_appl_data/tables/mstr_places.eex.sql",
    "instance/msbms_appl_data/tables/mstr_persons.eex.sql",
    "instance/msbms_appl_data/tables/mstr_contacts.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_selling_entities.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_purchasing_entities.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_staffing_entities.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_banking_entities.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_inventory_places.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_workplace_places.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_fulfillment_places.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_person_roles.eex.sql",
    "instance/msbms_syst_data/tables/syst_person_logins.eex.sql",
    "instance/msbms_appl_data/tables/mstr_person_contact_roles.eex.sql",
]
