# Source File: buildplans.cmp_msbms_syst_instance_mgr_integration_test.toml
# Location:    musebms/database/buildplans.cmp_msbms_syst_instance_mgr_integration_test.toml
# Project:     Muse Systems Business Management System
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com :: https://muse.systems

##
##  NOTE:  This build plan exists only to facilitate automated testing,
##         continuous integration, and other similar development & testing
##         activities.  It is not used to build released software.
##

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    {type = "plan", file = "all/subplans.common_init.toml"},
    {type = "plan", file = "components/system/msbms_syst_enums/subplans.msbms_syst_enums.toml"},
    {type = "plan", file = "components/system/msbms_syst_instance_mgr/subplans.msbms_syst_instance_mgr.toml"},
]

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 821
sponsor_modification = 0
load_files = [
    "components/system/msbms_syst_enums/testing_support/test_privileges.eex.sql",
    "components/system/msbms_syst_instance_mgr/testing_support/test_privileges.eex.sql",
    "components/system/msbms_syst_instance_mgr/testing_support/test_data_integration_test.eex.sql",
]
