# Source File: buildplans.mssub_mcp.toml
# Location:    musebms/database/buildplans.mssub_mcp.toml
# Project:     Muse Systems Business Management System
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com :: https://muse.systems

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    #
    # Database Initialization
    #

    {type = "plan", file = "all/subplans.common_init.toml"},
    "subsystems/mssub_mcp/dbinit/initial_privileges.eex.sql",

    #
    # MscmpSystSettings
    #

    {type = "plan", file = "components/system/mscmp_syst_settings/subplans.mscmp_syst_settings.toml"},
    "subsystems/mssub_mcp/components/mscmp_syst_settings/privileges.eex.sql",

    #
    # MscmpSystEnums
    #

    {type = "plan", file = "components/system/mscmp_syst_enums/subplans.mscmp_syst_enums.toml"},
    "subsystems/mssub_mcp/components/mscmp_syst_enums/privileges.eex.sql",

    #
    # MscmpSystFeatures
    #

    {type = "plan", file = "components/system/mscmp_syst_features/subplans.mscmp_syst_features.toml"},
    "subsystems/mssub_mcp/gen_seed_data/initialize_feature_mapping.eex.sql",

    #
    # MscmpSystInstanceMgr
    #

    {type = "plan", file = "components/system/mscmp_syst_instance/subplans.mscmp_syst_instance.toml"},
    "subsystems/mssub_mcp/components/mscmp_syst_instance/privileges.eex.sql",

    #
    # MscmpSystAuthentication
    #

    {type = "plan", file = "components/system/mscmp_syst_authn/subplans.mscmp_syst_authn.toml"},
    "subsystems/mssub_mcp/components/mscmp_syst_authn/privileges.eex.sql",
]
