# Source File: buildplans.app_msbms_instance.toml
# Location:    musebms/database/buildplans.app_msbms_instance.toml
# Project:     Muse Systems Business Management System
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com :: https://muse.systems

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    #
    # Database Initialization
    #

    {type = "plan", file = "all/subplans.common_init.toml"},
    "application/msbms_instance/gen_dbinit/msbms_instance_schemata.eex.sql",

    #
    # MsbmsSystSettings
    #

    {type = "plan", file = "components/system/msbms_syst_settings/subplans.msbms_syst_settings.toml"},
    "application/msbms_instance/components/msbms_syst_settings/privileges.eex.sql",

    #
    # MsbmsSystEnums
    #

    {type = "plan", file = "components/system/msbms_syst_enums/subplans.msbms_syst_enums.toml"},
    "application/msbms_instance/components/msbms_syst_enums/privileges.eex.sql",

    #
    #  MsbmsSystFeatures
    #

    {type = "plan", file = "components/system/msbms_syst_features/subplans.msbms_syst_features.toml"},
     "application/msbms_instance/gen_seed_data/initialize_feature_mapping.eex.sql",

    #
    # MsbmsSystFormats
    #

    {type = "plan", file = "components/system/msbms_syst_formats/subplans.msbms_syst_formats.toml"},

    #
    # MsbmsSystNumberings
    #

    {type = "plan", file = "components/system/msbms_syst_numberings/subplans.msbms_syst_numberings.toml"},

    #
    # Instance Schema Loading
    #
    # TODO: The files below will likely end up in components of their own or
    #       minimally have subplans of their own.  For now, however, we'll leave
    #       as-is as any more concrete form than what already exists is
    #       speculative.

     "application/msbms_instance/mod_syst/seed_data/initialize_enum_login_states.eex.sql",
     "application/msbms_instance/mod_syst/seed_data/initialize_enum_interaction_types.eex.sql",
     "application/msbms_instance/mod_syst/seed_data/initialize_enum_interface_types.eex.sql",

     "application/msbms_instance/mod_brm/seed_data/initialize_enum_address_states.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_contact_states.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_contact_types.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_entity_person_roles.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_entity_place_roles.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_entity_states.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_entity_types.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_person_contact_roles.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_person_states.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_person_types.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_place_address_roles.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_place_states.eex.sql",
     "application/msbms_instance/mod_brm/seed_data/initialize_enum_place_types.eex.sql",

     "application/msbms_instance/mod_accounting/seed_data/initialize_enum_fiscal_period_states.eex.sql",
     "application/msbms_instance/mod_accounting/seed_data/initialize_enum_fiscal_year_states.eex.sql",
     "application/msbms_instance/mod_accounting/seed_data/initialize_enum_fiscal_year_types.eex.sql",

     "application/msbms_instance/mod_syst/msbms_syst_data/syst_interaction_logs/syst_interaction_logs.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_countries/mstr_countries.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_country_address_format_assocs/mstr_country_address_format_assocs.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_country_phone_format_assocs/mstr_country_phone_format_assocs.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_country_name_format_assocs/mstr_country_name_format_assocs.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_entities/mstr_entities.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_places/mstr_places.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_persons/mstr_persons.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_contacts/mstr_contacts.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_entity_selling_entities/mstr_entity_selling_entities.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_entity_purchasing_entities/mstr_entity_purchasing_entities.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_entity_staffing_entities/mstr_entity_staffing_entities.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_entity_banking_entities/mstr_entity_banking_entities.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_entity_inventory_places/mstr_entity_inventory_places.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_entity_workplace_places/mstr_entity_workplace_places.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_entity_fulfillment_places/mstr_entity_fulfillment_places.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_entity_person_roles/mstr_entity_person_roles.eex.sql",
     "application/msbms_instance/mod_syst/msbms_syst_data/syst_person_logins/syst_person_logins.eex.sql",
     "application/msbms_instance/mod_brm/msbms_appl_data/mstr_person_contact_roles/mstr_person_contact_roles.eex.sql",
]
