# Source File: buildplans.instance.toml
# Location:    musebms/database/buildplans.instance.toml
# Project:     musebms
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com  : : https: //muse.systems

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    "instance/dbinit/database_initial_setup.eex.sql",
    "instance/dbinit/create_database_schemata.eex.sql",

    "common/msbms_syst_priv/collations/variant_insensitive.eex.sql",
    "common/msbms_syst_priv/functions/get_exception_details.eex.sql",
    "common/msbms_syst_priv/trigger_functions/multi_table/trig_b_iu_set_diagnostic_columns.eex.sql",

    "common/msbms_syst_data/tables/syst_settings.eex.sql",
    "common/msbms_syst_data/tables/syst_relations.eex.sql",
    "common/msbms_syst_data/tables/syst_feature_map_levels.eex.sql",
    "common/msbms_syst_data/tables/syst_feature_map.eex.sql",
    "common/msbms_syst_priv/trigger_functions/multi_table/trig_a_iu_feature_map_level_assignable_check.eex.sql",
    "common/msbms_syst_data/tables/syst_feature_relation_assigns.eex.sql",
    "common/msbms_syst_data/tables/syst_feature_setting_assigns.eex.sql",

    "common/msbms_syst_data/tables/syst_complex_formats.eex.sql",
    "common/msbms_syst_data/tables/syst_complex_format_values.eex.sql",
    "common/msbms_syst_priv/trigger_functions/multi_table/trig_a_iu_complex_format_value_check.eex.sql",

    "common/msbms_syst_data/tables/syst_enums.eex.sql",
    "common/msbms_syst_data/tables/syst_enum_functional_types.eex.sql",
    "common/msbms_syst_priv/trigger_functions/syst_enum_values/trig_a_iu_syst_enum_values_check_functional_type.eex.sql",
    "common/msbms_syst_data/tables/syst_enum_values.eex.sql",
    "common/msbms_syst_priv/trigger_functions/multi_table/trig_a_iu_enum_value_check.eex.sql",
    "common/msbms_syst_data/tables/syst_feature_enum_assigns.eex.sql",
    "common/msbms_syst_priv/functions/initialize_enum.eex.sql",

    "common/msbms_syst_data/tables/syst_numberings.eex.sql",
    "common/msbms_syst_priv/trigger_functions/syst_numbering_sequences/trig_a_i_syst_numbering_sequence_create_value.eex.sql",
    "common/msbms_syst_data/tables/syst_numbering_sequences.eex.sql",
    "common/msbms_syst_data/tables/syst_numbering_sequence_values.eex.sql",
    "common/msbms_syst_priv/functions/get_next_sequence_value.eex.sql",
    "common/msbms_syst_priv/functions/set_next_sequence_value.eex.sql",
    "common/msbms_syst_data/tables/syst_numbering_segment_types.eex.sql",
    "common/msbms_syst_data/tables/syst_numbering_segments.eex.sql",

    "instance/seed_data/system/initialize_feature_mapping.eex.sql",
    "instance/seed_data/system/initialize_numbering_segment_types.eex.sql",

    "instance/seed_data/system/initialize_enum_login_states.eex.sql",
    "instance/seed_data/system/initialize_enum_interaction_types.eex.sql",
    "instance/seed_data/system/initialize_enum_interface_types.eex.sql",

    "instance/seed_data/brm/initialize_enum_address_states.eex.sql",
    "instance/seed_data/brm/initialize_enum_contact_states.eex.sql",
    "instance/seed_data/brm/initialize_enum_contact_types.eex.sql",
    "instance/seed_data/brm/initialize_enum_entity_person_roles.eex.sql",
    "instance/seed_data/brm/initialize_enum_entity_place_roles.eex.sql",
    "instance/seed_data/brm/initialize_enum_entity_states.eex.sql",
    "instance/seed_data/brm/initialize_enum_entity_types.eex.sql",
    "instance/seed_data/brm/initialize_enum_person_contact_roles.eex.sql",
    "instance/seed_data/brm/initialize_enum_person_states.eex.sql",
    "instance/seed_data/brm/initialize_enum_person_types.eex.sql",
    "instance/seed_data/brm/initialize_enum_place_address_roles.eex.sql",
    "instance/seed_data/brm/initialize_enum_place_states.eex.sql",
    "instance/seed_data/brm/initialize_enum_place_types.eex.sql",

    "instance/seed_data/accounting/initialize_enum_fiscal_period_states.eex.sql",
    "instance/seed_data/accounting/initialize_enum_fiscal_year_states.eex.sql",
    "instance/seed_data/accounting/initialize_enum_fiscal_year_types.eex.sql",

    "instance/msbms_syst_data/tables/syst_interaction_logs.eex.sql",
    "instance/msbms_appl_data/tables/mstr_countries.eex.sql",
    "instance/msbms_appl_data/tables/mstr_country_address_format_assocs.eex.sql",
    "instance/msbms_appl_data/tables/mstr_country_phone_format_assocs.eex.sql",
    "instance/msbms_appl_data/tables/mstr_country_name_format_assocs.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entities.eex.sql",
    "instance/msbms_appl_data/tables/mstr_places.eex.sql",
    "instance/msbms_appl_data/tables/mstr_persons.eex.sql",
    "instance/msbms_appl_data/tables/mstr_contacts.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_selling_entities.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_purchasing_entities.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_staffing_entities.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_banking_entities.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_inventory_places.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_workplace_places.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_fulfillment_places.eex.sql",
    "instance/msbms_appl_data/tables/mstr_entity_person_roles.eex.sql",
    "instance/msbms_syst_data/tables/syst_person_logins.eex.sql",
    "instance/msbms_appl_data/tables/mstr_person_contact_roles.eex.sql",
]
