# Source File: buildplans.test_type_five.toml
# Location:    musebms/components/system/msbms_syst_datastore/database/buildplans.test_type_five.toml
# Project:     Muse Systems Business Management System
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com  : : https: //muse.systems

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    "test_common/test01.a.common.eex.sql",
    {type = "plan", file = "subplans.test_type_five_sub_a.toml"}
]

[[build_plan]]
release              = 1
version              = 2
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    {type = "plan", file = "subplans.test_type_five_sub_a.toml"}
]


[[build_plan]]
release              = 1
version              = 3
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    {type = "plan", file = "subplans.test_type_five_sub_a.toml"},
    {type = "sql", file = "test_type_five/test11.a.test_type_five.eex.sql"}
]