# Source File: subplans.cmp_msbms_syst_features.toml
# Location:    musebms/database/subplans.cmp_msbms_syst_features.toml
# Project:     Muse Systems Business Management System
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com :: https://muse.systems

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [
    "cmp_msbms_syst_features/msbms_syst_data/syst_relations/syst_relations.eex.sql",
    "cmp_msbms_syst_features/msbms_syst_data/syst_feature_map_levels/syst_feature_map_levels.eex.sql",
    "cmp_msbms_syst_features/msbms_syst_data/syst_feature_map/syst_feature_map.eex.sql",
    "cmp_msbms_syst_features/msbms_syst_priv/trigger_functions/trig_a_iu_feature_map_level_assignable_check.eex.sql",
    "cmp_msbms_syst_features/msbms_syst_data/syst_feature_relation_assigns/syst_feature_relation_assigns.eex.sql",
    "cmp_msbms_syst_features/msbms_syst_data/syst_feature_setting_assigns/syst_feature_setting_assigns.eex.sql",
    "cmp_msbms_syst_features/msbms_syst_data/syst_feature_enum_assigns/syst_feature_enum_assigns.eex.sql",

    "cmp_msbms_syst_features/msbms_syst/api_views/syst_feature_setting_assigns/trig_i_i_syst_feature_setting_assigns.eex.sql",
    "cmp_msbms_syst_features/msbms_syst/api_views/syst_feature_setting_assigns/trig_i_u_syst_feature_setting_assigns.eex.sql",
    "cmp_msbms_syst_features/msbms_syst/api_views/syst_feature_setting_assigns/trig_i_d_syst_feature_setting_assigns.eex.sql",
    "cmp_msbms_syst_features/msbms_syst/api_views/syst_feature_setting_assigns/syst_feature_setting_assigns.eex.sql",
]
