services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/musebms:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: musesystems-insecure-password
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432

volumes:
  postgres-data:
