-- File:        syst_nav_actions.eex.sql
-- Location:    musebms/database/components/system/mscmp_syst_nav/ms_syst/api_views/syst_nav_actions/syst_nav_actions.eex.sql
-- Project:     Muse Systems Business Management System
--
-- Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
-- This file may include content copyrighted and licensed from third parties.
--
-- See the LICENSE file in the project root for license terms and conditions.
-- See the NOTICE file in the project root for copyright ownership information.
--
-- muse.information@musesystems.com :: https://muse.systems

CREATE VIEW ms_syst.syst_nav_actions AS
SELECT
    id
  , internal_name
  , display_name
  , external_name
  , action_group_id
  , command
  , command_config
  , command_aliases
  , command_search
  , syst_defined
  , syst_description
  , user_maintainable
  , user_description
  , diag_timestamp_created
  , diag_role_created
  , diag_timestamp_modified
  , diag_wallclock_modified
  , diag_role_modified
  , diag_row_version
  , diag_update_count
FROM ms_syst_data.syst_nav_actions;

ALTER VIEW ms_syst.syst_nav_actions OWNER TO <%= ms_owner %>;

REVOKE ALL ON TABLE ms_syst.syst_nav_actions FROM PUBLIC;

CREATE TRIGGER a50_trig_i_i_syst_nav_actions
    INSTEAD OF INSERT ON ms_syst.syst_nav_actions
    FOR EACH ROW EXECUTE PROCEDURE ms_syst.trig_i_i_syst_nav_actions();

CREATE TRIGGER a50_trig_i_u_syst_nav_actions
    INSTEAD OF UPDATE ON ms_syst.syst_nav_actions
    FOR EACH ROW EXECUTE PROCEDURE ms_syst.trig_i_u_syst_nav_actions();

CREATE TRIGGER a50_trig_i_d_syst_nav_actions
    INSTEAD OF DELETE ON ms_syst.syst_nav_actions
    FOR EACH ROW EXECUTE PROCEDURE ms_syst.trig_i_d_syst_nav_actions();

DO
$DOCUMENTATION$
DECLARE
    -- View
    v_view_config ms_syst_priv.comments_config_apiview;

    -- View Columns
    v_action_group_id ms_syst_priv.comments_config_apiview_column;
    v_command         ms_syst_priv.comments_config_apiview_column;
    v_command_config  ms_syst_priv.comments_config_apiview_column;
    v_command_aliases ms_syst_priv.comments_config_apiview_column;
    v_command_search  ms_syst_priv.comments_config_apiview_column;

BEGIN

    --
    -- API View Config
    --

    v_view_config.table_schema := 'ms_syst_data';
    v_view_config.table_name   := 'syst_nav_actions';
    v_view_config.view_schema  := 'ms_syst';
    v_view_config.view_name    := 'syst_nav_actions';
    v_view_config.syst_records := TRUE;
    v_view_config.syst_update  := TRUE;

    --
    -- Column Configs
    --

    v_action_group_id.column_name  := 'action_group_id';
    v_action_group_id.required     := TRUE;
    v_action_group_id.user_update  := FALSE;
    v_action_group_id.supplemental :=
$DOC$This column is part of a composite key.  The combined values of
`action_group_id` and `command` must be unique.  The `command` column may be
`NULL` which excludes the record from this uniqueness check (`NULL` values are
distinct).$DOC$;

    v_command.column_name  := 'command';
    v_command.supplemental :=
$DOC$This column is part of a composite key.  The combined values of
`action_group_id` and `command` must be unique.  The `command` column may be
`NULL` which excludes the record from this uniqueness check (`NULL` values are
distinct).$DOC$;

    v_command_config.column_name      := 'command_config';

    v_command_aliases.column_name      := 'command_aliases';
    v_command_aliases.syst_update_mode := 'maint';

    v_command_search.column_name      := 'command_search';
    v_command_search.default_value    := 'Autogenerated';
    v_command_search.user_insert      := FALSE;
    v_command_search.user_update      := FALSE;

    v_view_config.columns :=
        ARRAY [
              v_action_group_id
            , v_command
            , v_command_config
            , v_command_aliases
            , v_command_search
            ]::ms_syst_priv.comments_config_apiview_column[];

    PERFORM ms_syst_priv.generate_comments_apiview( v_view_config );

END;
$DOCUMENTATION$;
