-- File:        reset_dev_database.psql
-- Location:    musebms/app_server/components/system/mscmp_syst_authn/database_utils/reset_dev_database.psql
-- Project:     Muse Systems Business Management System
--
-- Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
-- This file may include content copyrighted and licensed from third parties.
--
-- See the LICENSE file in the project root for license terms and conditions.
-- See the NOTICE file in the project root for copyright ownership information.
--
-- muse.information@musesystems.com :: https://muse.systems

-- Note that this script currently exists to support CI testing
-- A more robust script should be produced to walk users though
-- the initial setup of the global database and ms_sys_login
-- user.
--
-- Do not use this script to setup a production environment.
\set ON_ERROR_STOP true
\c postgres

DROP DATABASE IF EXISTS mscmp_syst_authn;

\ir ../../../../../tools/database_scripts/reset_dev_database.psql

DROP ROLE IF EXISTS mscmp_syst_authn_owner;
DROP ROLE IF EXISTS mscmp_syst_authn_app_user;


\ir ../../../../../tools/database_scripts/bootstrap_database.psql
