-- Note that this script currently exists to support CI testing
-- A more robust script should be produced to walk users though
-- the initial setup of the MSBMS database and msbms_sys_login
-- user.
--
-- Do not use this script to setup a production environment.
\set ON_ERROR_STOP true
\c postgres

-- Clean-up testing database objects

DROP DATABASE IF EXISTS test_msmcp_build;
DROP DATABASE IF EXISTS test_instance_build;

DROP ROLE IF EXISTS msmcp_build_api_user;
DROP ROLE IF EXISTS msmcp_build_app_user;
DROP ROLE IF EXISTS msmcp_build_owner;

DROP ROLE IF EXISTS msbms_build_api_user;
DROP ROLE IF EXISTS msbms_build_app_user;
DROP ROLE IF EXISTS msbms_build_owner;

-- Clean-up dev-support database objects

DROP DATABASE IF EXISTS msmcp_dev;
DROP DATABASE IF EXISTS msbms_dev;

DROP ROLE IF EXISTS msmcp_dev_api_user;
DROP ROLE IF EXISTS msmcp_dev_app_user;
DROP ROLE IF EXISTS msmcp_dev_owner;

DROP ROLE IF EXISTS msbms_dev_api_user;
DROP ROLE IF EXISTS msbms_dev_app_user;
DROP ROLE IF EXISTS msbms_dev_owner;

-- General clean-up

DROP ROLE IF EXISTS muse_syst_access;
DROP ROLE IF EXISTS muse_syst_dba;

\ir bootstrap_database.psql
