-- File:        app1.01.01.000.0000MT.000.eex.sql
-- Location:    musebms/database/components/system/mscmp_syst_instance/testing_support/app1/app1.01.01.000.0000MT.000.eex.sql
-- Project:     Muse Systems Business Management System
--
-- Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
-- This file may include content copyrighted and licensed from third parties.
--
-- See the LICENSE file in the project root for license terms and conditions.
-- See the NOTICE file in the project root for copyright ownership information.
--
-- muse.information@musesystems.com  :: https://muse.systems

DO
$MIGRATION$
    BEGIN
            CREATE SCHEMA IF NOT EXISTS testing
                AUTHORIZATION <%= app1_owner %>;

            REVOKE USAGE ON SCHEMA testing FROM PUBLIC;
            GRANT USAGE ON SCHEMA testing TO <%= app1_owner %>;
            GRANT USAGE ON SCHEMA testing TO <%= app1_appusr %>;
            GRANT USAGE ON SCHEMA testing TO <%= app1_apiusr %>;

            COMMENT ON SCHEMA testing IS
            $DOC$A testing schema for use during MscmpSystInstance integration testing.$DOC$;

            CREATE TABLE testing.test_header
            (
                 id
                    bigint
                    GENERATED BY DEFAULT AS IDENTITY
                    CONSTRAINT test_header_pk PRIMARY KEY
                ,test_value
                    text
                    NOT NULL
            );

            ALTER TABLE testing.test_header OWNER TO <%= app1_owner %>;

            REVOKE ALL ON TABLE testing.test_header FROM public;
            GRANT ALL ON TABLE testing.test_header TO <%= app1_owner %>;
            GRANT ALL ON TABLE testing.test_header TO <%= app1_appusr %>;
            GRANT ALL ON TABLE testing.test_header TO <%= app1_apiusr %>;

            COMMENT ON
                TABLE testing.test_header IS
            $DOC$A testing header table for MscmpSystInstance integration testing.$DOC$;

            COMMENT ON
                COLUMN testing.test_header.id IS
            $DOC$The record's primary key.  The definitive identifier of the record in the system.$DOC$;

            COMMENT ON
                COLUMN testing.test_header.test_value IS
            $DOC$A simple testing value which has no well defined meaning.$DOC$;

    END;
$MIGRATION$;
