-- File:        test_app.01.01.000.0000MT.000.eex.sql
-- Location:    musebms/database/subsystems/mssub_mcp/testing_support/test_app/test_app.01.01.000.0000MT.000.eex.sql
-- Project:     Muse Systems Business Management System
--
-- Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
-- This file may include content copyrighted and licensed from third parties.
--
-- See the LICENSE file in the project root for license terms and conditions.
-- See the NOTICE file in the project root for copyright ownership information.
--
-- muse.information@musesystems.com :: https://muse.systems

DO
$MIGRATION$
    BEGIN
            CREATE SCHEMA IF NOT EXISTS testing
                AUTHORIZATION <%= test_app_owner %>;

            REVOKE USAGE ON SCHEMA testing FROM PUBLIC;
            GRANT USAGE ON SCHEMA testing TO <%= test_app_owner %>;
            GRANT USAGE ON SCHEMA testing TO <%= test_app_access %>;

            COMMENT ON SCHEMA testing IS
            $DOC$A testing schema for use during MscmpSystInstance integration testing.$DOC$;

            CREATE TABLE testing.test_header
            (
                 id
                    bigint
                    GENERATED BY DEFAULT AS IDENTITY
                    CONSTRAINT test_header_pk PRIMARY KEY
                ,test_value
                    text
                    NOT NULL
            );

            ALTER TABLE testing.test_header OWNER TO <%= test_app_owner %>;

            REVOKE ALL ON TABLE testing.test_header FROM public;
            GRANT ALL ON TABLE testing.test_header TO <%= test_app_owner %>;
            GRANT ALL ON TABLE testing.test_header TO <%= test_app_access %>;

            COMMENT ON
                TABLE testing.test_header IS
            $DOC$A testing header table for MscmpSystInstance integration testing.$DOC$;

            COMMENT ON
                COLUMN testing.test_header.id IS
            $DOC$The record's primary key.  The definitive identifier of the record in the system.$DOC$;

            COMMENT ON
                COLUMN testing.test_header.test_value IS
            $DOC$A simple testing value which has no well defined meaning.$DOC$;

    END;
$MIGRATION$;
