-- Note that this script currently exists to support CI testing
-- A more robust script should be produced to walk users though
-- the initial setup of the global database and msbms_sys_login
-- user.
--
-- Do not use this script to setup a production environment.
\set ON_ERROR_STOP true
\c postgres

DROP DATABASE IF EXISTS mscmp_syst_authn;

DROP ROLE IF EXISTS ms_syst_access;
DROP ROLE IF EXISTS ms_syst_dba;

DROP ROLE IF EXISTS mscmp_syst_authn_owner;
DROP ROLE IF EXISTS mscmp_syst_authn_app_user;


\ir bootstrap_database.psql
