# Muse Systems Business Management System Startup Options
#
# For deployment, simply copy this file to: ms_startup_options.toml and
# replace the values with those that are appropriate for your deployment.
#
# Please note that this file is security sensitive an it should be protected
# accordingly.

# The server_name of the dbserver which will host the global database.  If this
# server is not found or has not been bootstrapped, the system will not start.
global_dbserver_name = "testing_server"

# A password used by the global Datastore Context database roles to connect to
# the database.  This value should be at least 16 bytes of data.
global_db_password = "(eXI0BU&elq1(mvw"

# The number of database connections to establish for accessing the global
# database.
global_db_pool_size = 10

# Used for peppering access account credentials when appropriate.  This value
# should be changed for each installation of the application and also kept in
# a secure place.  If this value is ever lost, existing access accounts will in
# many cases no longer be able to authenticate to the system.  This value should
# contain at least 32 bytes of data.
global_pepper_value  = "jTtEdXRExP5YXHeARQ1W66lP6wDc9GyOvhFPvwnHhtc="

#===============================================================================
# Database Servers Section
#-------------------------------------------------------------------------------
#
#
#
#===============================================================================

[[dbserver]]
# The identifier of the database server which will also appear in user
# interfaces.
server_name                    = "testing_server"

# If this database server hosts instance databases and the value here is true,
# the system will make database connections for any instance databases existing
# on the server.  If false, those instances will not be available via the
# application server.  Note the global database is always started regardless of
# the setting here.
start_server_instances         = false

# Indicates which system instance classes the database server may be used to
# host.  None, one, or many of the following values are allowed:
#
#     * primary - this class is used to host production workloads.  At least one
#       database server must be configured to support primary class instances.
#       In many scenarios, this will be the only class needed.
#
#     * linked - instances which are child instances to a parent primary
#       instance.  Typically these are used for non-production instances which
#       are copies or otherwise reflect the parent instance.
#
#     * demo - indicates that the database server will host instances dedicated
#       to demonstration purposes.  In typical scenarios, this instance class
#       will not be used.
#
#     * reserved - designates that other, special use instances may be hosted by
#       the database server.  Under normal circumstances this value will not be
#       used.
#
# If no classes are configured for a database server, the server may not host
# any application instances though it may host the global database.
supported_instance_classes     = []

# The hostname/IP of the database server
db_host                        = "127.0.0.1"

# The port on which the database server is listening
db_port                        = 5432

# If true, sensitive information, such as username/password may be shown in
# some application logs or error displays
db_show_sensitive              = true

# The number of instance databases that may be hosted on the server.
db_max_instances               = 0

# A string of bytes used as part of the token generation for the system managed
# database user accounts.  Note that this value must be at least 32 bytes long
# and is ideally randomly generated.
server_salt                  = "sklMRkLXzMQgzqpMpJZPk31Js88su39U/mooAXALhj0="

# The database password used by the system for the connecting the
# ms_syst_privileged database user account on this database server.  This
# password must be at least 32 bytes long.
dbadmin_password               = "musesystems.publicly.known.insecure.devsupport.password"

# The number of pooled database connections to create for the dbadmin repo.
# This value should normally be quite low.
dbadmin_pool_size     = 1

