# Source File: manifest.toml
# Location:    musebms/database/manifest.toml
# Project:     musebms
#
# Copyright © Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from thrid parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com  : : https: //muse.systems

load_files = [
    "instance/dbinit/database_initial_setup.sql",
    "instance/dbinit/create_database_schemata.sql",
    "common/msbms_syst_priv/functions/get_exception_details.sql",
    "common/msbms_syst_priv/trigger_functions/trig_b_iu_set_diagnostic_columns.sql",
    "instance/msbms_syst_data/tables/syst_modules.sql",
    "instance/msbms_syst_data/tables/syst_feature_types.sql",
    "instance/msbms_syst_data/tables/syst_features.sql",
    "instance/msbms_syst_data/tables/syst_relations.sql",
    "instance/msbms_syst_data/tables/conf_system_settings.sql",
    "instance/msbms_syst_data/tables/syst_feature_relation_assigns.sql",
    "instance/msbms_syst_data/tables/enum_interface_types.sql",
    "instance/msbms_syst_data/tables/enum_interaction_types.sql",
    "instance/msbms_syst_data/tables/enum_login_states.sql",
    "instance/msbms_syst_data/tables/enum_authentication_types.sql",
    "instance/msbms_syst_data/tables/syst_interaction_logs.sql",
    "instance/msbms_appl_data/tables/conf_global_settings.sql",
    "instance/msbms_appl_data/tables/enum_entity_states.sql",
    "instance/msbms_appl_data/tables/enum_entity_types.sql",
    "instance/msbms_appl_data/tables/enum_person_states.sql",
    "instance/msbms_appl_data/tables/enum_person_types.sql",
    "instance/msbms_appl_data/tables/enum_place_states.sql",
    "instance/msbms_appl_data/tables/enum_place_types.sql",
    "instance/msbms_appl_data/tables/enum_address_states.sql",
    "instance/msbms_appl_data/tables/enum_entity_place_roles.sql",
    "instance/msbms_appl_data/tables/enum_entity_person_roles.sql",
    "instance/msbms_appl_data/tables/enum_place_address_roles.sql",
    "instance/msbms_appl_data/tables/enum_contact_states.sql",
    "instance/msbms_appl_data/tables/enum_contact_types.sql",
    "instance/msbms_appl_data/tables/enum_person_contact_roles.sql",
    "instance/msbms_appl_data/tables/enum_fiscal_year_states.sql",
    "instance/msbms_appl_data/tables/enum_fiscal_year_types.sql",
    "instance/msbms_appl_data/tables/enum_fiscal_period_states.sql",
    "instance/msbms_appl_data/tables/conf_address_formats.sql",
    "instance/msbms_appl_data/tables/conf_phone_formats.sql",
    "instance/msbms_appl_data/tables/conf_name_formats.sql",
    "instance/msbms_appl_data/tables/mstr_countries.sql",
    "instance/msbms_appl_data/tables/mstr_country_address_format_assocs.sql",
    "instance/msbms_appl_data/tables/mstr_country_phone_format_assocs.sql",
    "instance/msbms_appl_data/tables/mstr_country_name_format_assocs.sql",
    "instance/msbms_appl_data/tables/mstr_entities.sql",
    "instance/msbms_appl_data/tables/mstr_places.sql",
    "instance/msbms_appl_data/tables/mstr_persons.sql",
    "instance/msbms_appl_data/tables/mstr_contacts.sql",
    "instance/msbms_appl_data/tables/mstr_entity_selling_entities.sql",
    "instance/msbms_appl_data/tables/mstr_entity_purchasing_entities.sql",
    "instance/msbms_appl_data/tables/mstr_entity_staffing_entities.sql",
    "instance/msbms_appl_data/tables/mstr_entity_banking_entities.sql",
    "instance/msbms_appl_data/tables/mstr_entity_inventory_places.sql",
    "instance/msbms_appl_data/tables/mstr_entity_workplace_places.sql",
    "instance/msbms_appl_data/tables/mstr_entity_fulfillment_places.sql",
    "instance/msbms_appl_data/tables/mstr_entity_person_roles.sql",
    "instance/msbms_syst_data/tables/syst_person_logins.sql",
    "instance/msbms_syst_data/tables/syst_login_authenticators.sql",
    "instance/msbms_appl_data/tables/mstr_person_contact_roles.sql",
]
