load_files = [
    "dbinit/database_initial_setup.sql",
    "dbinit/create_database_schemata.sql",
    "msbms_syst_priv/functions/get_exception_details.sql",
    "msbms_syst_priv/trigger_functions/trig_b_iu_set_diagnostic_columns.sql",
    "msbms_syst_data/tables/app_modules.sql",
    "msbms_syst_data/tables/app_feature_types.sql",
    "msbms_syst_data/tables/app_features.sql",
    "msbms_syst_data/tables/app_relations.sql",
    "msbms_syst_data/tables/configs.sql",
    "msbms_syst_data/tables/app_feature_app_relation_assigns.sql",
    "msbms_syst_data/tables/enum_app_interface_types.sql",
    "msbms_syst_data/tables/enum_app_interaction_types.sql",
    "msbms_syst_data/tables/interaction_logs.sql",
    "msbms_appl_data/tables/configs.sql",
    "msbms_appl_data/tables/enum_relationship_states.sql",
    "msbms_appl_data/tables/enum_relationship_types.sql",
    "msbms_appl_data/tables/enum_person_states.sql",
    "msbms_appl_data/tables/enum_person_types.sql",
    "msbms_appl_data/tables/enum_facility_states.sql",
    "msbms_appl_data/tables/enum_facility_types.sql",
    "msbms_appl_data/tables/enum_address_states.sql",
]
