load_files = [
    "dbinit/database_initial_setup.sql",
    "dbinit/create_database_schemata.sql",
    "msbms_syst_priv/functions/get_exception_details.sql",
    "msbms_syst_priv/trigger_functions/trig_b_iu_set_diagnostic_columns.sql",
    "msbms_syst_data/tables/app_modules.sql",
    "msbms_syst_data/tables/app_feature_types.sql",
    "msbms_syst_data/tables/app_features.sql",
    "msbms_syst_data/tables/app_relations.sql",
]
