load_files = [
    "dbinit/database_initial_setup.sql",
    "dbinit/create_database_schemata.sql",
    "msbms_syst_priv/functions/get_exception_details.sql",
    "msbms_syst_priv/trigger_functions/trig_b_iu_set_diagnostic_columns.sql",
    "msbms_syst_data/tables/syst_modules.sql",
    "msbms_syst_data/tables/syst_feature_types.sql",
    "msbms_syst_data/tables/syst_features.sql",
    "msbms_syst_data/tables/syst_relations.sql",
    "msbms_syst_data/tables/conf_system_settings.sql",
    "msbms_syst_data/tables/syst_feature_relation_assigns.sql",
    "msbms_syst_data/tables/enum_interface_types.sql",
    "msbms_syst_data/tables/enum_interaction_types.sql",
    "msbms_syst_data/tables/enum_authentication_states",
    "msbms_syst_data/tables/enum_authentication_types",
    "msbms_syst_data/tables/syst_interaction_logs.sql",
    "msbms_appl_data/tables/conf_global_settings.sql",
    "msbms_appl_data/tables/enum_relationship_states.sql",
    "msbms_appl_data/tables/enum_relationship_types.sql",
    "msbms_appl_data/tables/enum_person_states.sql",
    "msbms_appl_data/tables/enum_person_types.sql",
    "msbms_appl_data/tables/enum_facility_states.sql",
    "msbms_appl_data/tables/enum_facility_types.sql",
    "msbms_appl_data/tables/enum_address_states.sql",
    "msbms_appl_data/tables/enum_relationship_facility_roles.sql",
    "msbms_appl_data/tables/enum_relationship_person_roles.sql",
    "msbms_appl_data/tables/enum_facility_address_roles.sql",
    "msbms_appl_data/tables/enum_contact_states.sql",
    "msbms_appl_data/tables/enum_contact_types.sql",
    "msbms_appl_data/tables/enum_contact_roles.sql",
    "msbms_appl_data/tables/enum_fiscal_year_states.sql",
    "msbms_appl_data/tables/enum_fiscal_year_types.sql",
    "msbms_appl_data/tables/enum_fiscal_period_states.sql",
    "msbms_appl_data/tables/mstr_relationships.sql",
    "msbms_appl_data/tables/mstr_relationship_customer_details.sql",
]
