name: Muse Systems BMS CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-msbms-build:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['24.0']
        elixir: ['1.12.2']
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: msbms_installer
          POSTGRES_PASSWORD: msbms_pass
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Build The Book
        uses: xu-cheng/latex-action@v2
        with:
          root_file: documentation/TheBook/main.tex
          latexmk_use_xelatex: true

      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Build Mix Dependencies
        run: mix deps.get
        working-directory: ./msbms

      - name: Database Load Script Build
        run: mix builddb
        working-directory: ./msbms

      - name: Load Database Load Script
        run: psql -h localhost -p 5432 -U msbms_installer postgres < tools/database_scripts/reset_dev_database.psql
        env:
          PGPASSWORD: msbms_pass
