name: MSBMS Application CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-msbms-apps-build:
    runs-on: ubuntu-latest
    name: Muse Systems BMS (OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}) CI
    strategy:
      matrix:
        otp: ['24.0']
        elixir: ['1.13.2']
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: msbms_installer
          POSTGRES_PASSWORD: msbms_pass
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      ########
      #
      # System Components
      #
      ########

      # msbms_syst_error
      - name: msbms_syst_error -- Build Mix Dependencies
        run: mix deps.get
        working-directory: ./components/system/msbms_syst_error

      - name: msbms_syst_error -- Run mix test
        run: mix test
        working-directory: ./components/system/msbms_syst_error

      # msbms_syst_options
      - name: msbms_syst_options -- Build Mix Dependencies
        run: mix deps.get
        working-directory: ./components/system/msbms_syst_options

      - name: msbms_syst_options -- Run mix test
        run: mix test
        working-directory: ./components/system/msbms_syst_options

      # msbms_syst_datastore
      - name: msbms_syst_datastore -- Build Mix Dependencies
        run: mix deps.get
        working-directory: ./components/system/msbms_syst_datastore

      - name: msbms_syst_datastore -- Run mix test
        run: mix test
        working-directory: ./components/system/msbms_syst_datastore

      ########
      #
      # Application
      #
      ########

      - name: msbms -- Build Mix Dependencies
        run: mix deps.get
        working-directory: ./application/msbms

      - name: msbms -- Run mix test
        run: mix test
        working-directory: ./application/msbms

      # - name: Database Load Script Build
      #   run: mix builddb
      #   working-directory: ./components/system/msbms_syst_error

      # - name: Load Database Load Script
      #   run: psql -h localhost -p 5432 -U msbms_installer postgres < tools/database_scripts/reset_dev_database.psql
      #   env:
      #     PGPASSWORD: msbms_pass
