name: MSBMS Application CI

on:
  push:
    branches: [next_version, versions]
  pull_request:
    branches: [next_version, versions]

env:
  MIX_ENV: test

jobs:
  test_system_components:
    runs-on: ubuntu-latest
    env:
      MSBMS_JOBNAME: system-components-${{ matrix.otp }}-${{ matrix.elixir }}-pg${{ matrix.postgres }}

    strategy:
      matrix:
        otp: ["27.3.4.3"]
        elixir: ["1.18.4"]
        postgres: ["18"]

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: testing_dba
          POSTGRES_PASSWORD: testing-dba-password
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install Elixir and OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install Hex and Rebar
        run: |
          mix local.hex --force
          mix local.rebar --force

      - name: Install MSBMS Build Tools
        run: |
          mix archive.install tools/build_tools/msbms_build_lib-1.1.1.ez --force

      - name: Reset and Initialize Database
        run: |
          mix msbms.db.clean --reset \
            --base-dir . \
            --db-host localhost \
            --db-port 5432 \
            --db-user testing_dba \
            --db-name postgres \
            --dbadmin-password musesystems-insecure-publicly-known-password
        env:
          PGPASSWORD: testing-dba-password

      - name: Restore PLT cache
        id: plt_cache
        uses: actions/cache/restore@v3
        with:
          key: plt-${{ env.MSBMS_JOBNAME }}
          restore-keys: |
            plt-${{ env.MSBMS_JOBNAME }}
          path: |
            **/priv/plts

      - name: Install Dependencies
        run: |
          mix msbms.elixir.deps --install \
            --base-dir . \
            --component-file .github/component-lists/system-components.txt

      - name: Run Tests for System Components
        run: |
          mix msbms.elixir.test --all \
            --base-dir . \
            --component-file .github/component-lists/system-components.txt

      - name: Save PLT cache
        id: plt_cache_save
        uses: actions/cache/save@v3
        if: steps.plt_cache.outputs.cache-hit != 'true'
        with:
          key: plt-${{ env.MSBMS_JOBNAME }}
          path: |
            **/priv/plts

  # test_application_components:
  #   runs-on: ubuntu-latest
  #   env:
  #     MSBMS_JOBNAME: application-components-${{ matrix.otp }}-${{ matrix.elixir }}-pg${{ matrix.postgres }}

  #   strategy:
  #     matrix:
  #       otp: ["27.3.4.3"]
  #       elixir: ["1.18.4"]
  #       postgres: ["18"]

  #   services:
  #     postgres:
  #       image: postgres:${{ matrix.postgres }}
  #       env:
  #         POSTGRES_USER: testing_dba
  #         POSTGRES_PASSWORD: testing-dba-password
  #         POSTGRES_PORT: 5432
  #       ports:
  #         - 5432:5432
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5

  #   steps:
  #     - name: Checkout repository code
  #       uses: actions/checkout@v3

  #     - name: Install Elixir and OTP
  #       uses: erlef/setup-beam@v1
  #       with:
  #         otp-version: ${{ matrix.otp }}
  #         elixir-version: ${{ matrix.elixir }}

  #     - name: Install Hex and Rebar
  #       run: |
  #         mix local.hex --force
  #         mix local.rebar --force

  #     - name: Install MSBMS Build Tools
  #       run: |
  #         mix archive.install tools/build_tools/msbms_build_lib-1.1.1.ez --force

  #     - name: Reset and Initialize Database
  #       run: |
  #         mix msbms.db.clean --reset \
  #           --base-dir . \
  #           --db-host localhost \
  #           --db-port 5432 \
  #           --db-user testing_dba \
  #           --db-name postgres \
  #           --dbadmin-password musesystems-insecure-publicly-known-password
  #       env:
  #         PGPASSWORD: testing-dba-password

  #     - name: Run Tests for Application Components
  #       run: |
  #         mix msbms.elixir.test --all \
  #           --base-dir . \
  #           --component-file .github/component-lists/application-components.txt

  # test_applications:
  #   runs-on: ubuntu-latest
  #   env:
  #     MSBMS_JOBNAME: applications-${{ matrix.otp }}-${{ matrix.elixir }}-pg${{ matrix.postgres }}

  #   strategy:
  #     matrix:
  #       otp: ["27.3.4.3"]
  #       elixir: ["1.18.4"]
  #       postgres: ["18"]

  #   services:
  #     postgres:
  #       image: postgres:${{ matrix.postgres }}
  #       env:
  #         POSTGRES_USER: testing_dba
  #         POSTGRES_PASSWORD: testing-dba-password
  #         POSTGRES_PORT: 5432
  #       ports:
  #         - 5432:5432
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5

  #   steps:
  #     - name: Checkout repository code
  #       uses: actions/checkout@v3

  #     - name: Install Elixir and OTP
  #       uses: erlef/setup-beam@v1
  #       with:
  #         otp-version: ${{ matrix.otp }}
  #         elixir-version: ${{ matrix.elixir }}

  #     - name: Install Hex and Rebar
  #       run: |
  #         mix local.hex --force
  #         mix local.rebar --force

  #     - name: Install MSBMS Build Tools
  #       run: |
  #         mix archive.install tools/build_tools/msbms_build_lib-1.1.1.ez --force

  #     - name: Reset and Initialize Database
  #       run: |
  #         mix msbms.db.clean --reset \
  #           --base-dir . \
  #           --db-host localhost \
  #           --db-port 5432 \
  #           --db-user testing_dba \
  #           --db-name postgres \
  #           --dbadmin-password musesystems-insecure-publicly-known-password
  #       env:
  #         PGPASSWORD: testing-dba-password

  #     - name: Run Tests for Applications
  #       run: |
  #         mix msbms.elixir.test --all \
  #           --base-dir . \
  #           --component-file .github/component-lists/applications.txt

  # test_platform:
  #   runs-on: ubuntu-latest
  #   env:
  #     MSBMS_JOBNAME: platform-${{ matrix.otp }}-${{ matrix.elixir }}-pg${{ matrix.postgres }}

  #   strategy:
  #     matrix:
  #       otp: ["27.3.4.3"]
  #       elixir: ["1.18.4"]
  #       postgres: ["18"]

  #   services:
  #     postgres:
  #       image: postgres:${{ matrix.postgres }}
  #       env:
  #         POSTGRES_USER: testing_dba
  #         POSTGRES_PASSWORD: testing-dba-password
  #         POSTGRES_PORT: 5432
  #       ports:
  #         - 5432:5432
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5

  #   steps:
  #     - name: Checkout repository code
  #       uses: actions/checkout@v3

  #     - name: Install Elixir and OTP
  #       uses: erlef/setup-beam@v1
  #       with:
  #         otp-version: ${{ matrix.otp }}
  #         elixir-version: ${{ matrix.elixir }}

  #     - name: Install Hex and Rebar
  #       run: |
  #         mix local.hex --force
  #         mix local.rebar --force

  #     - name: Install MSBMS Build Tools
  #       run: |
  #         mix archive.install tools/build_tools/msbms_build_lib-1.1.1.ez --force

  #     - name: Reset and Initialize Database
  #       run: |
  #         mix msbms.db.clean --reset \
  #           --base-dir . \
  #           --db-host localhost \
  #           --db-port 5432 \
  #           --db-user testing_dba \
  #           --db-name postgres \
  #           --dbadmin-password musesystems-insecure-publicly-known-password
  #       env:
  #         PGPASSWORD: testing-dba-password

  #     - name: Run Tests for Platform
  #       run: |
  #         mix msbms.elixir.test --all \
  #           --base-dir . \
  #           --component-file .github/component-lists/platform.txt
