name: MSBMS Application CI

on:
  push:
    branches: [next_version, versions]
  pull_request:
    branches: [next_version, versions]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  syst-app-components:
    uses: ./.github/workflows/component-test.yml
    with:
      component-group: syst-app

  syst-auth-components:
    uses: ./.github/workflows/component-test.yml
    with:
      component-group: syst-auth

  syst-core-components:
    uses: ./.github/workflows/component-test.yml
    with:
      component-group: syst-core

  syst-platform-components:
    uses: ./.github/workflows/component-test.yml
    with:
      component-group: syst-platform
