name: MSBMS Application CI

on:
  push:
    branches: [next_version, versions]
  pull_request:
    branches: [next_version, versions]

env:
  MIX_ENV: test

jobs:
  test_system_components:
    runs-on: ubuntu-latest
    env:
      MSBMS_BASEDIR: ./app_server/components/system
      MSBMS_JOBNAME: system-components-${{ matrix.otp }}-${{ matrix.elixir }}

    strategy:
      matrix:
        otp: ["26.2.1"]
        elixir: ["1.16.0"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testing_dba
          POSTGRES_PASSWORD: testing-dba-password
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Initialize Database
        run: psql -f tools/database_scripts/bootstrap_database.psql --set dbadmin_password='musesystems-insecure-publicly-known-password' postgresql://testing_dba:testing-dba-password@localhost:5432/postgres

      - name: Run Tests for System Components
        run: |
          # Make the build script executable
          chmod +x tools/build_tools/msbms_build.exs

          # Run tests for all system components
          ./tools/build_tools/msbms_build.exs --base-dir ${{ env.MSBMS_BASEDIR }} --test --ci

  test_business_components:
    runs-on: ubuntu-latest
    env:
      MSBMS_BASEDIR: ./app_server/components/business
      MSBMS_JOBNAME: business-components-${{ matrix.otp }}-${{ matrix.elixir }}

    strategy:
      matrix:
        otp: ["26.2.1"]
        elixir: ["1.16.0"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testing_dba
          POSTGRES_PASSWORD: testing-dba-password
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Initialize Database
        run: psql -f tools/database_scripts/bootstrap_database.psql --set dbadmin_password='musesystems-insecure-publicly-known-password' postgresql://testing_dba:testing-dba-password@localhost:5432/postgres

      - name: Run Tests for Business Components
        run: |
          # Make the build script executable
          chmod +x tools/build_tools/msbms_build.exs

          # Run tests for all business components
          ./tools/build_tools/msbms_build.exs --base-dir ${{ env.MSBMS_BASEDIR }} --test --ci

  test_subsystems:
    runs-on: ubuntu-latest
    env:
      MSBMS_BASEDIR: ./app_server/subsystems
      MSBMS_JOBNAME: subsystems-${{ matrix.otp }}-${{ matrix.elixir }}

    strategy:
      matrix:
        otp: ["26.2.1"]
        elixir: ["1.16.0"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testing_dba
          POSTGRES_PASSWORD: testing-dba-password
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Initialize Database
        run: psql -f tools/database_scripts/bootstrap_database.psql --set dbadmin_password='musesystems-insecure-publicly-known-password' postgresql://testing_dba:testing-dba-password@localhost:5432/postgres

      - name: Run Tests for Subsystems
        run: |
          # Make the build script executable
          chmod +x tools/build_tools/msbms_build.exs

          # Run tests for all subsystems
          ./tools/build_tools/msbms_build.exs --base-dir ${{ env.MSBMS_BASEDIR }} --test --ci
