# Muse Systems Business Management System Startup Options
#
# For deployment, simply copy this file to: msbms_startup_options.toml and
# replace the values with those that are appropriate for your deployment.
#
# Please note that this file is security sensitive an it should be protected
# accordingly.

#===============================================================================
# Global Admin Section
#-------------------------------------------------------------------------------
#
#
#
#===============================================================================

[global_admin]
# The database password used by the system for the connecting the msbms_syst_dba
# database user account to the various database servers.  This password must be
# at least 32 bytes long and should be the same on all servers managed by the
# application server.
dbadmin_password      = ""

# The number of pooled database connections to create for the dbadmin repo.
# This value should normally be quite low.
dbadmin_pool_size     = 1

# The server_name of the db_server which will host the global database.  If this
# server is not found or has not been bootstrapped, the system will not start.
global_db_server_name = "GLOBAL-DB"

#===============================================================================
# Database Servers Section
#-------------------------------------------------------------------------------
#
#
#
#===============================================================================

[[db_server]]
# The identifier of the database server which will also appear in user
# interfaces.
server_name                    = "GLOBAL-DB"

# If this database server hosts instance databases and the value here is true,
# the system will make database connections for any instance databases existing
# on the server.  If false, those instances will not be available via the
# application server.  Note the global database is always started regardless of
# the setting here.
start_server_instances         = false

# If true, the server may host production instance databases.  The value here is
# used to filter the available servers by instance type, especially during the
# process that assigns instances to servers.
instance_production_db_server  = false

# If true, the server may host non-production instance databases.  The value
# here is used to filter the available servers by instance type, especially
# during the process that assigns instances to servers.
instance_sandbox_db_server     = false

# The hostname/IP of the database server
db_host                        = "127.0.0.1"

# The port on which the database server is listening
db_port                        = 5432

# If true, senstive information, such as username/password may be shown in
# some application logs or error displays
db_show_sensitive              = false

# This value is used to set the database connection minimum log level.
# Valid values are:
#     emergency, alert, critical, error, warning, notice, info, debug
db_log_level                   = "error"

# The number of instance databases that may be hosted on the server.
db_max_instances               = 0

# The default global/instance app_user pool size that the application will start
# each of the database connections with.
db_default_app_user_pool_size  = 3

# The default global/instance api_user pool size that the application will start
# each of the database connections with.
db_default_api_user_pool_size  = 2

# The default global/instance app_admin pool size that the application will
# start each of the database connections with.
db_default_app_admin_pool_size = 2

# The default global/instance api_admin pool size that the application will
# start each of the database connections with.
db_default_api_admin_pool_size = 2

# A string of bytes used as part of the token generation for the system managed
# database user accounts.  Note that this value must be at least 32 bytes long
# and is ideally randomly generated.
instance_salt                  = ""

[[db_server]]
# The identifier of the database server which will also appear in user
# interfaces.
server_name                    = "INSTANCE-DB"

# If this database server hosts instance databases and the value here is true,
# the system will make database connections for any instance databases existing
# on the server.  If false, those instances will not be available via the
# application server.  Note the global database is always started regardless of
# the setting here.
start_server_instances         = true

# If true, the server may host production instance databases.  The value here is
# used to filter the available servers by instance type, especially during the
# process that assigns instances to servers.
instance_production_db_server  = true

# If true, the server may host non-production instance databases.  The value
# here is used to filter the available servers by instance type, especially
# during the process that assigns instances to servers.
instance_sandbox_db_server     = true

# The hostname/IP of the database server
db_host                        = "127.0.0.1"

# The port on which the database server is listening
db_port                        = 5432

# If true, senstive information, such as username/password may be shown in
# some application logs or error displays
db_show_sensitive              = false

# This value is used to set the database connection minimum log level.
# Valid values are:
#     emergency, alert, critical, error, warning, notice, info, debug
db_log_level                   = "error"

# The number of instance databases that may be hosted on the server.
db_max_instances               = 0

# The default global/instance app_user pool size that the application will start
# each of the database connections with.
db_default_app_user_pool_size  = 5

# The default global/instance api_user pool size that the application will start
# each of the database connections with.
db_default_api_user_pool_size  = 3

# The default global/instance app_admin pool size that the application will
# start each of the database connections with.
db_default_app_admin_pool_size = 3

# The default global/instance api_admin pool size that the application will
# start each of the database connections with.
db_default_api_admin_pool_size = 3

# A string of bytes used as part of the token generation for the system managed
# database user accounts.  Note that this value must be at least 32 bytes long
# and is ideally randomly generated.
instance_salt                  = ""