# Muse Systems Business Management System Startup Options
#
# For deployment, simply copy this file to: msbms_startup_options.toml and
# replace the values with those that are appropriate for your deployment.
#
# Please note that this file is security sensitive an it should be protected
# accordingly.

[global_admin]
db_host           = "localhost"       # The hostname/IP of the database server
db_port           = 5432              # The port on which the database server is listening
db_pass           = "msbms_pass"      # The database password for the connecting database user
db_show_sensitive = false             # If true, senstive information, such as username/password may be shown in some cases
db_log_level      = "debug"           # A logging level for various database events from the application
db_pool_size      = 3                 # The size of the database connection pool

[instance_admin]
# A salt used for certain service authentication scenarios, min length is 32 bytes
instance_salt     = "Replace this!"
